FROM busybox

LABEL maintainer="Dita Pelaj <dita_s@live.com> and Luísa Hörlle de Castro <luisa@iservport.com>"
LABEL description="Activation Base for AI Project 'Appointment or Disappointment'"
LABEL course="Advanced AI-based Application Systems"

RUN mkdir -p /activationBase

COPY activation_data.csv /activationBase/
COPY README.activationBase.md /activationBase/

# CMD ["sh"]
