version: "3.9"

services:
  knowledge_base:
    image: docker.io/hoerllel/tmp:knowledgebase_appointmentordisappointment
    volumes:
       - ai_system:/tmp
    command:
      - sh
      - "-c"
      - |
        rm -rf /tmp/knowledgeBase/ && mkdir -p /tmp/knowledgeBase/ && cp -r /tmp/knowledgeBase/ /tmp/;

  activation_base:
    image: docker.io/hoerllel/tmp:activationbase_appointmentordisappointment
    volumes:
       - ai_system:/tmp
    command:
      - sh
      - "-c"
      - |
        rm -rf /tmp/activationBase/ && mkdir -p /tmp/activationBase/ && cp -r /tmp/activationBase/ /tmp/;

  code_base:
    image: docker.io/hoerllel/tmp:codebase_appointmentordisappointment
    volumes:
       - ai_system:/tmp
    depends_on:
      - "knowledge_base"
      - "activation_base"
    command:
      - sh
      - "-c"
      - |
        rm -rf /tmp/codeBase/ && mkdir -p /tmp/codeBase/ && cp -r /tmp/activationBase/ /tmp/codeBase/;
        python3 /tmp/codeBase/applyOLS.py;

volumes:
  ai_system:
    external: true