version: "3.9"

services:
  knowledge_base:
    image: docker.io/hoerllel/tmp:knowledgebase_appointmentordisappointment
    volumes:
      - ai_system:/tmp/knowledgeBase
    entrypoint: ["sh", "-c", "ls -R /tmp/knowledgeBase"]

  activation_base:
    image: docker.io/hoerllel/tmp:activationbase_appointmentordisappointment
    volumes:
      - ai_system:/tmp/activationBase
    entrypoint: ["sh", "-c", "ls -R /tmp/activationBase"]

  code_base:
    image: docker.io/hoerllel/tmp:codebase_appointmentordisappointment
    volumes:
      - ai_system:/tmp/codeBase
    depends_on:
      - knowledge_base
      - activation_base
    entrypoint: ["sh", "-c", "ls -R /tmp/codeBase && python3 /tmp/codeBase/applyANN.py"]

volumes:
  ai_system:
    driver: local
