version: '3.9'

services:
  learning_base:
    image: docker.io/hoerllel/tmp:learningbase_appointmentordisappointment
    volumes:
      - ai_system:/tmp/learningBase
    entrypoint: ["sh", "-c", "ls -R /tmp/learningBase"]

  activation_base:
    image: docker.io/hoerllel/tmp:activationbase_appointmentordisappointment
    volumes:
      - ai_system:/tmp/activationBase
    entrypoint: ["sh", "-c", "ls -R /tmp/activationBase"]

  knowledge_base:
    image: docker.io/hoerllel/tmp:knowledgebase_appointmentordisappointment
    volumes:
      - ai_system:/tmp/knowledgeBase
    entrypoint: ["sh", "-c", "ls -R /tmp/knowledgeBase"]

  code_base:
    image: docker.io/hoerllel/tmp:codebase_appointmentordisappointment
    volumes:
      - ai_system:/tmp/activationBase
    entrypoint: ["sh", "-c", "ls -R /tmp/activationBase"]

volumes:
  ai_system:
    driver: local
